/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_strace.h                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: wirare <wirare@42angouleme.fr>             +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/08/30 20:02:23 by wirare            #+#    #+#             */
/*   Updated: 2025/08/31 22:02:07 by ellanglo         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
#pragma once
#include <sys/syscall.h>
#include <syscall.h>

#define SYS_futex_waitv 449
#define SYS_set_mempolicy_home_node 450
#define SYS_cachestat 451

typedef unsigned long long int u64;

typedef enum
{
		SAT_VA_ARGS,
        SAT_STRUCT_KEXEC_SEGMENT_PTR,
        SAT_INT,
        SAT_STRUCT_SIGALTSTACK_PTR,
        SAT_UNION_BPF_ATTR_PTR,
        SAT_STRUCT_USER_MSGHDR_PTR,
        SAT_CHAR_PTR,
        SAT_STRUCT__KERNEL_ITIMERSPEC_PTR,
        SAT_CAP_USER_HEADER_T,
        SAT_CONST_CAP_USER_DATA_T,
        SAT_STRUCT_IOCB_PTR,
        SAT_MQD_T,
        SAT_SIZE_T,
        SAT_OFF_T,
        SAT_STRUCT_PERF_EVENT_ATTR_PTR,
        SAT_SIGSET_T_PTR,
        SAT_STRUCT_OLD_UTSNAME_PTR,
        SAT_KEY_T,
        SAT_UNSIGNED_INT,
        SAT_INT_PTR,
        SAT_LOFF_T_PTR,
        SAT_UNSIGNED_INT_PTR,
        SAT_TIME_T_PTR,
        SAT_STRUCT_SCHED_PARAM_PTR,
        SAT_AIO_CONTEXT_T,
        SAT_OFF_T_PTR,
        SAT_QID_T,
        SAT_STRUCT__KERNEL_TIMESPEC_PTR,
        SAT_STRUCT__KERNEL_TIMEX_PTR,
        SAT_STRUCT_MQ_ATTR_PTR,
        SAT_STRUCT_RLIMIT64_PTR,
        SAT_STRUCT_STATFS_PTR,
        SAT_CONST_STRUCT__KERNEL_ITIMERSPEC_PTR,
        SAT_KEY_SERIAL_T,
        SAT_TIMER_T,
        SAT_STRUCT_RUSAGE_PTR,
        SAT_UNSIGNED,
        SAT_GID_T,
        SAT_CONST_STRUCT_SIGALTSTACK_PTR,
        SAT_STRUCT_EPOLL_EVENT_PTR,
        SAT_SIZE_T_PTR,
        SAT_STRUCT_GETCPU_CACHE_PTR,
        SAT_LONG,
        SAT_U32_PTR,
        SAT_STRUCT_FILE_HANDLE_PTR,
        SAT_STRUCT_RLIMIT_PTR,
        SAT_CONST_STRUCT_MQ_ATTR_PTR,
        SAT_STRUCT_MSQID_DS_PTR,
        SAT_STRUCT_IO_EVENT_PTR,
        SAT_STRUCT_SYSINFO_PTR,
        SAT_STRUCT_TIMEZONE_PTR,
        SAT_STRUCT_SOCKADDR_PTR,
        SAT_UID_T,
        SAT_CONST_STRUCT_RLIMIT64_PTR,
        SAT_CONST_VOID_PTR_PTR,
        SAT_CONST_VOID_PTR,
        SAT_CAP_USER_DATA_T,
        SAT_STRUCT_USTAT_PTR,
        SAT_STRUCT_ROBUST_LIST_HEAD_PTR,
        SAT_CONST_SIGSET_T_PTR,
        SAT_STRUCT_UTIMBUF_PTR,
        SAT_CONST_STRUCT_SIGEVENT_PTR,
        SAT_CLOCKID_T,
        SAT_TIMER_T_PTR_,
        SAT_CONST_STRUCT_IOVEC_PTR,
        SAT_STRUCT_ITIMERVAL_PTR,
        SAT_CONST_STRUCT__KERNEL_TIMESPEC_PTR,
        SAT_UNSIGNED_PTR,
        SAT_CONST_CHAR_PTR_,
        SAT_STRUCT_STATX_PTR,
        SAT_FD_SET_PTR,
        SAT_STRUCT_LINUX_DIRENT_PTR,
        SAT_CONST_INT_PTR,
        SAT__S32,
        SAT_STRUCT_STAT_PTR,
        SAT_GID_T_PTR,
        SAT_U64,
        SAT_SIGINFO_T_PTR,
        SAT_STRUCT_TMS_PTR,
        SAT_U32,
        SAT_STRUCT_SEMBUF_PTR,
        SAT_STRUCT_SHMID_DS_PTR,
        SAT_STRUCT_TIMEVAL_PTR,
        SAT_STRUCT__OLD_KERNEL_STAT_PTR,
        SAT_STRUCT_LINUX_DIRENT64_PTR,
        SAT_CONST_CHAR_PTR_CONST_PTR,
        SAT_STRUCT_SIGACTION_PTR,
        SAT_AIO_CONTEXT_T_PTR,
        SAT_LOFF_T,
        SAT_STRUCT_MSGBUF_PTR,
        SAT_STRUCT_POLLFD_PTR,
        SAT_CONST_CHAR_PTR,
        SAT_PID_T,
        SAT_STRUCT_MMSGHDR_PTR,
        SAT_RWF_T,
        SAT_UNSIGNED_CHAR_PTR_,
        SAT_STRUCT_SCHED_ATTR_PTR,
        SAT_CONST_UNSIGNED_LONG_PTR,
        SAT_CONST_STRUCT_SIGACTION_PTR,
        SAT_STRUCT_IOCB_PTR_PTR,
        SAT_UMODE_T,
        SAT_STRUCT_ROBUST_LIST_HEAD_PTR_PTR,
        SAT_UID_T_PTR,
        SAT_VOID_PTR,
        SAT_STRUCT_SIGINFO_PTR,
        SAT_UNSIGNED_LONG_PTR,
		SAT_STRUCT_USER_DESC_PTR,
		SAT_CONST_STRUCT_TIMESPEC_PTR,
		SAT_STRUCT_RSEQ_PTR,
		SAT_STRUCT_IO_URING_PARAMS_PTR,
		SAT_STRUCT_CLONE_ARGS_PTR,
		SAT_STRUCT_OPEN_HOW_PTR,
		SAT_STRUCT_IOVEC_PTR,
		SAT_STRUCT_MOUNT_ATTR_PTR,
		SAT_STRUCT_DQBLK_PTR,
		SAT_CONST_STRUCT_LANDLOCK_RULESET_ATTR_PTR,
		SAT_STRUCT_FUTEX_WAITV_PTR,
		SAT_CACHESTAT_RANGE__USER_PTR,
		SAT_CACHESTAT__USER_PTR,
		SAT_UNSIGNED_LONG,
		SAT_STRUCT_SIGEVENT_PTR,
		SAT_NO_ARG,
}	t_syscall_arg_type;


typedef struct 
{
	t_syscall_arg_type	arg0;
	t_syscall_arg_type	arg1;
	t_syscall_arg_type	arg2;
	t_syscall_arg_type	arg3;
	t_syscall_arg_type	arg4;
	t_syscall_arg_type	arg5;
}	t_syscall_args;

typedef struct 
{
	u64 syscall_number;
	const char *syscall_name;
	t_syscall_args args;
}	t_syscall_info;

#define _CONCAT(_a, _b) _a##_b
#define CONCAT(a, b) _CONCAT(a, b)

#define MAKE_SYS_INFO_STRUCT(name, ...)													\
	(t_syscall_info)																	\
	{																					\
		.syscall_number = CONCAT(SYS_, name),											\
		.syscall_name = #name,															\
		.args =																			\
			(t_syscall_args)															\
			{																			\
				.arg0 = SAT_NO_ARG,														\
				.arg1 = SAT_NO_ARG,														\
				.arg2 = SAT_NO_ARG,														\
				.arg3 = SAT_NO_ARG,														\
				.arg4 = SAT_NO_ARG,														\
				.arg5 = SAT_NO_ARG,	__VA_ARGS__											\
			}																			\
	}

typedef void (*pfn_printer)(u64) ;

#define DEFINE_PRINTER(type) [type] = type##_printer,
#define DECLARE_PRINTER(type) void type##_printer(u64 data __attribute__((unused)))
#define GET_ARG(nb) arg#nb

char* resolve_x64_syscall_num(long long syscall_number);
t_syscall_info get_syscall_info(u64 syscall_number);
void print(t_syscall_arg_type type, u64 data);
int get_num_arg(u64 syscall_number);

DECLARE_PRINTER(SAT_VA_ARGS);
DECLARE_PRINTER(SAT_STRUCT_KEXEC_SEGMENT_PTR);
DECLARE_PRINTER(SAT_INT);
DECLARE_PRINTER(SAT_STRUCT_SIGALTSTACK_PTR);
DECLARE_PRINTER(SAT_UNION_BPF_ATTR_PTR);
DECLARE_PRINTER(SAT_STRUCT_USER_MSGHDR_PTR);
DECLARE_PRINTER(SAT_CHAR_PTR);
DECLARE_PRINTER(SAT_STRUCT__KERNEL_ITIMERSPEC_PTR);
DECLARE_PRINTER(SAT_CAP_USER_HEADER_T);
DECLARE_PRINTER(SAT_CONST_CAP_USER_DATA_T);
DECLARE_PRINTER(SAT_STRUCT_IOCB_PTR);
DECLARE_PRINTER(SAT_MQD_T);
DECLARE_PRINTER(SAT_SIZE_T);
DECLARE_PRINTER(SAT_OFF_T);
DECLARE_PRINTER(SAT_STRUCT_PERF_EVENT_ATTR_PTR);
DECLARE_PRINTER(SAT_SIGSET_T_PTR);
DECLARE_PRINTER(SAT_STRUCT_OLD_UTSNAME_PTR);
DECLARE_PRINTER(SAT_KEY_T);
DECLARE_PRINTER(SAT_UNSIGNED_INT);
DECLARE_PRINTER(SAT_INT_PTR);
DECLARE_PRINTER(SAT_LOFF_T_PTR);
DECLARE_PRINTER(SAT_UNSIGNED_INT_PTR);
DECLARE_PRINTER(SAT_TIME_T_PTR);
DECLARE_PRINTER(SAT_STRUCT_SCHED_PARAM_PTR);
DECLARE_PRINTER(SAT_AIO_CONTEXT_T);
DECLARE_PRINTER(SAT_OFF_T_PTR);
DECLARE_PRINTER(SAT_QID_T);
DECLARE_PRINTER(SAT_STRUCT__KERNEL_TIMESPEC_PTR);
DECLARE_PRINTER(SAT_STRUCT__KERNEL_TIMEX_PTR);
DECLARE_PRINTER(SAT_STRUCT_MQ_ATTR_PTR);
DECLARE_PRINTER(SAT_STRUCT_RLIMIT64_PTR);
DECLARE_PRINTER(SAT_STRUCT_STATFS_PTR);
DECLARE_PRINTER(SAT_CONST_STRUCT__KERNEL_ITIMERSPEC_PTR);
DECLARE_PRINTER(SAT_KEY_SERIAL_T);
DECLARE_PRINTER(SAT_TIMER_T);
DECLARE_PRINTER(SAT_STRUCT_RUSAGE_PTR);
DECLARE_PRINTER(SAT_UNSIGNED);
DECLARE_PRINTER(SAT_GID_T);
DECLARE_PRINTER(SAT_CONST_STRUCT_SIGALTSTACK_PTR);
DECLARE_PRINTER(SAT_STRUCT_EPOLL_EVENT_PTR);
DECLARE_PRINTER(SAT_SIZE_T_PTR);
DECLARE_PRINTER(SAT_STRUCT_GETCPU_CACHE_PTR);
DECLARE_PRINTER(SAT_LONG);
DECLARE_PRINTER(SAT_U32_PTR);
DECLARE_PRINTER(SAT_STRUCT_FILE_HANDLE_PTR);
DECLARE_PRINTER(SAT_STRUCT_RLIMIT_PTR);
DECLARE_PRINTER(SAT_CONST_STRUCT_MQ_ATTR_PTR);
DECLARE_PRINTER(SAT_STRUCT_MSQID_DS_PTR);
DECLARE_PRINTER(SAT_STRUCT_IO_EVENT_PTR);
DECLARE_PRINTER(SAT_STRUCT_SYSINFO_PTR);
DECLARE_PRINTER(SAT_STRUCT_TIMEZONE_PTR);
DECLARE_PRINTER(SAT_STRUCT_SOCKADDR_PTR);
DECLARE_PRINTER(SAT_UID_T);
DECLARE_PRINTER(SAT_CONST_STRUCT_RLIMIT64_PTR);
DECLARE_PRINTER(SAT_CONST_VOID_PTR_PTR);
DECLARE_PRINTER(SAT_CONST_VOID_PTR);
DECLARE_PRINTER(SAT_CAP_USER_DATA_T);
DECLARE_PRINTER(SAT_STRUCT_USTAT_PTR);
DECLARE_PRINTER(SAT_STRUCT_ROBUST_LIST_HEAD_PTR);
DECLARE_PRINTER(SAT_CONST_SIGSET_T_PTR);
DECLARE_PRINTER(SAT_STRUCT_UTIMBUF_PTR);
DECLARE_PRINTER(SAT_CONST_STRUCT_SIGEVENT_PTR);
DECLARE_PRINTER(SAT_CLOCKID_T);
DECLARE_PRINTER(SAT_TIMER_T_PTR_);
DECLARE_PRINTER(SAT_CONST_STRUCT_IOVEC_PTR);
DECLARE_PRINTER(SAT_STRUCT_ITIMERVAL_PTR);
DECLARE_PRINTER(SAT_CONST_STRUCT__KERNEL_TIMESPEC_PTR);
DECLARE_PRINTER(SAT_UNSIGNED_PTR);
DECLARE_PRINTER(SAT_CONST_CHAR_PTR_);
DECLARE_PRINTER(SAT_STRUCT_STATX_PTR);
DECLARE_PRINTER(SAT_FD_SET_PTR);
DECLARE_PRINTER(SAT_STRUCT_LINUX_DIRENT_PTR);
DECLARE_PRINTER(SAT_CONST_INT_PTR);
DECLARE_PRINTER(SAT_UNSIGNED_LONG);
DECLARE_PRINTER(SAT_STRUCT_SIGEVENT_PTR);
DECLARE_PRINTER(SAT__S32);
DECLARE_PRINTER(SAT_STRUCT_STAT_PTR);
DECLARE_PRINTER(SAT_GID_T_PTR);
DECLARE_PRINTER(SAT_U64);
DECLARE_PRINTER(SAT_SIGINFO_T_PTR);
DECLARE_PRINTER(SAT_STRUCT_TMS_PTR);
DECLARE_PRINTER(SAT_U32);
DECLARE_PRINTER(SAT_STRUCT_SEMBUF_PTR);
DECLARE_PRINTER(SAT_STRUCT_SHMID_DS_PTR);
DECLARE_PRINTER(SAT_STRUCT_TIMEVAL_PTR);
DECLARE_PRINTER(SAT_STRUCT__OLD_KERNEL_STAT_PTR);
DECLARE_PRINTER(SAT_STRUCT_LINUX_DIRENT64_PTR);
DECLARE_PRINTER(SAT_CONST_CHAR_PTR_CONST_PTR);
DECLARE_PRINTER(SAT_STRUCT_SIGACTION_PTR);
DECLARE_PRINTER(SAT_AIO_CONTEXT_T_PTR);
DECLARE_PRINTER(SAT_LOFF_T);
DECLARE_PRINTER(SAT_STRUCT_MSGBUF_PTR);
DECLARE_PRINTER(SAT_STRUCT_POLLFD_PTR);
DECLARE_PRINTER(SAT_CONST_CHAR_PTR);
DECLARE_PRINTER(SAT_PID_T);
DECLARE_PRINTER(SAT_STRUCT_MMSGHDR_PTR);
DECLARE_PRINTER(SAT_RWF_T);
DECLARE_PRINTER(SAT_UNSIGNED_CHAR_PTR_);
DECLARE_PRINTER(SAT_STRUCT_SCHED_ATTR_PTR);
DECLARE_PRINTER(SAT_CONST_UNSIGNED_LONG_PTR);
DECLARE_PRINTER(SAT_CONST_STRUCT_SIGACTION_PTR);
DECLARE_PRINTER(SAT_STRUCT_IOCB_PTR_PTR);
DECLARE_PRINTER(SAT_UMODE_T);
DECLARE_PRINTER(SAT_STRUCT_ROBUST_LIST_HEAD_PTR_PTR);
DECLARE_PRINTER(SAT_UID_T_PTR);
DECLARE_PRINTER(SAT_VOID_PTR);
DECLARE_PRINTER(SAT_STRUCT_SIGINFO_PTR);
DECLARE_PRINTER(SAT_UNSIGNED_LONG_PTR);
DECLARE_PRINTER(SAT_STRUCT_USER_DESC_PTR);
DECLARE_PRINTER(SAT_NO_ARG);
DECLARE_PRINTER(SAT_CONST_STRUCT_TIMESPEC_PTR);
DECLARE_PRINTER(SAT_STRUCT_RSEQ_PTR);
DECLARE_PRINTER(SAT_STRUCT_IO_URING_PARAMS_PTR);
DECLARE_PRINTER(SAT_STRUCT_CLONE_ARGS_PTR);
DECLARE_PRINTER(SAT_STRUCT_OPEN_HOW_PTR);
DECLARE_PRINTER(SAT_STRUCT_IOVEC_PTR);
DECLARE_PRINTER(SAT_STRUCT_MOUNT_ATTR_PTR);
DECLARE_PRINTER(SAT_STRUCT_DQBLK_PTR);
DECLARE_PRINTER(SAT_CONST_STRUCT_LANDLOCK_RULESET_ATTR_PTR);
DECLARE_PRINTER(SAT_STRUCT_FUTEX_WAITV_PTR);
DECLARE_PRINTER(SAT_CACHESTAT_RANGE__USER_PTR);
DECLARE_PRINTER(SAT_CACHESTAT__USER_PTR);
