/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   get_syscall_info.c                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ellanglo <ellanglo@42angouleme.fr>         +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/08/31 17:55:54 by ellanglo          #+#    #+#             */
/*   Updated: 2025/09/01 21:36:12 by ellanglo         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
#include <ft_strace.h>
#include <sys/syscall.h>

inline t_syscall_info __attribute__((const)) get_syscall_info(u64 syscall_number)
{
	static const t_syscall_info info_table[] = {
		[SYS_shmdt] = MAKE_SYS_INFO_STRUCT(shmdt, .arg0 = SAT_CHAR_PTR),
		[SYS_setsid] = MAKE_SYS_INFO_STRUCT(setsid,),
		[SYS_msgget] = MAKE_SYS_INFO_STRUCT(msgget, .arg0 = SAT_KEY_T, .arg1 = SAT_INT),
		[SYS_read] = MAKE_SYS_INFO_STRUCT(read, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T),
		[SYS_write] = MAKE_SYS_INFO_STRUCT(write, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T),
		[SYS_open] = MAKE_SYS_INFO_STRUCT(open, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_INT, .arg2 = SAT_UMODE_T),
		[SYS_close] = MAKE_SYS_INFO_STRUCT(close, .arg0 = SAT_UNSIGNED_INT),
		[SYS_stat] = MAKE_SYS_INFO_STRUCT(stat, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_PTR),
		[SYS_fstat] = MAKE_SYS_INFO_STRUCT(fstat, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_PTR),
		[SYS_lstat] = MAKE_SYS_INFO_STRUCT(lstat, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_PTR),
		[SYS_poll] = MAKE_SYS_INFO_STRUCT(poll, .arg0 = SAT_PTR, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_INT),
		[SYS_lseek] = MAKE_SYS_INFO_STRUCT(lseek, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_OFF_T, .arg2 = SAT_UNSIGNED_INT),
		[SYS_mmap] = MAKE_SYS_INFO_STRUCT(mmap, .arg0 = SAT_PTR, .arg1 = SAT_SIZE_T, .arg2 = SAT_INT, .arg3 = SAT_INT, .arg4 = SAT_INT, .arg5 = SAT_OFF_T),
		[SYS_mprotect] = MAKE_SYS_INFO_STRUCT(mprotect, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_munmap] = MAKE_SYS_INFO_STRUCT(munmap, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T),
		[SYS_brk] = MAKE_SYS_INFO_STRUCT(brk, .arg0 = SAT_UNSIGNED_LONG),
		[SYS_rt_sigaction] = MAKE_SYS_INFO_STRUCT(rt_sigaction, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T),
		[SYS_rt_sigprocmask] = MAKE_SYS_INFO_STRUCT(rt_sigprocmask, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T),
		[SYS_rt_sigreturn] = MAKE_SYS_INFO_STRUCT(rt_sigreturn, .arg0 = SAT_VA_ARGS),
		[SYS_ioctl] = MAKE_SYS_INFO_STRUCT(ioctl, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_pread64] = MAKE_SYS_INFO_STRUCT(pread64, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_LOFF_T),
		[SYS_pwrite64] = MAKE_SYS_INFO_STRUCT(pwrite64, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_LOFF_T),
		[SYS_readv] = MAKE_SYS_INFO_STRUCT(readv, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_writev] = MAKE_SYS_INFO_STRUCT(writev, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_access] = MAKE_SYS_INFO_STRUCT(access, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_INT),
		[SYS_pipe] = MAKE_SYS_INFO_STRUCT(pipe, .arg0 = SAT_PTR),
		[SYS_select] = MAKE_SYS_INFO_STRUCT(select, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR, .arg3 = SAT_PTR, .arg4 = SAT_PTR),
		[SYS_sched_yield] = MAKE_SYS_INFO_STRUCT(sched_yield,),
		[SYS_mremap] = MAKE_SYS_INFO_STRUCT(mremap, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_msync] = MAKE_SYS_INFO_STRUCT(msync, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T, .arg2 = SAT_INT),
		[SYS_mincore] = MAKE_SYS_INFO_STRUCT(mincore, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T, .arg2 = SAT_UNSIGNED_CHAR_PTR),
		[SYS_madvise] = MAKE_SYS_INFO_STRUCT(madvise, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T, .arg2 = SAT_INT),
		[SYS_shmget] = MAKE_SYS_INFO_STRUCT(shmget, .arg0 = SAT_KEY_T, .arg1 = SAT_SIZE_T, .arg2 = SAT_INT),
		[SYS_shmat] = MAKE_SYS_INFO_STRUCT(shmat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT),
		[SYS_shmctl] = MAKE_SYS_INFO_STRUCT(shmctl, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_PTR),
		[SYS_dup] = MAKE_SYS_INFO_STRUCT(dup, .arg0 = SAT_UNSIGNED_INT),
		[SYS_dup2] = MAKE_SYS_INFO_STRUCT(dup2, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT),
		[SYS_pause] = MAKE_SYS_INFO_STRUCT(pause,),
		[SYS_nanosleep] = MAKE_SYS_INFO_STRUCT(nanosleep, .arg0 = SAT_PTR, .arg1 = SAT_PTR),
		[SYS_getitimer] = MAKE_SYS_INFO_STRUCT(getitimer, .arg0 = SAT_INT, .arg1 = SAT_PTR),
		[SYS_alarm] = MAKE_SYS_INFO_STRUCT(alarm, .arg0 = SAT_UNSIGNED_INT),
		[SYS_setitimer] = MAKE_SYS_INFO_STRUCT(setitimer, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_getpid] = MAKE_SYS_INFO_STRUCT(getpid,),
		[SYS_sendfile] = MAKE_SYS_INFO_STRUCT(sendfile, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T),
		[SYS_socket] = MAKE_SYS_INFO_STRUCT(socket, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_INT),
		[SYS_connect] = MAKE_SYS_INFO_STRUCT(connect, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_INT),
		[SYS_accept] = MAKE_SYS_INFO_STRUCT(accept, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_sendto] = MAKE_SYS_INFO_STRUCT(sendto, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_UNSIGNED, .arg4 = SAT_PTR, .arg5 = SAT_INT),
		[SYS_recvfrom] = MAKE_SYS_INFO_STRUCT(recvfrom, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_UNSIGNED, .arg4 = SAT_PTR, .arg5 = SAT_PTR),
		[SYS_sendmsg] = MAKE_SYS_INFO_STRUCT(sendmsg, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED),
		[SYS_recvmsg] = MAKE_SYS_INFO_STRUCT(recvmsg, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED),
		[SYS_shutdown] = MAKE_SYS_INFO_STRUCT(shutdown, .arg0 = SAT_INT, .arg1 = SAT_INT),
		[SYS_bind] = MAKE_SYS_INFO_STRUCT(bind, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_INT),
		[SYS_listen] = MAKE_SYS_INFO_STRUCT(listen, .arg0 = SAT_INT, .arg1 = SAT_INT),
		[SYS_getsockname] = MAKE_SYS_INFO_STRUCT(getsockname, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_getpeername] = MAKE_SYS_INFO_STRUCT(getpeername, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_socketpair] = MAKE_SYS_INFO_STRUCT(socketpair, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_INT, .arg3 = SAT_PTR),
		[SYS_setsockopt] = MAKE_SYS_INFO_STRUCT(setsockopt, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_INT, .arg3 = SAT_CHAR_PTR, .arg4 = SAT_INT),
		[SYS_getsockopt] = MAKE_SYS_INFO_STRUCT(getsockopt, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_INT, .arg3 = SAT_CHAR_PTR, .arg4 = SAT_PTR),
		[SYS_clone] = MAKE_SYS_INFO_STRUCT(clone, .arg0 = SAT_UNSIGNED, .arg1 = SAT_UNSIGNED, .arg2 = SAT_PTR, .arg3 = SAT_PTR, .arg4 = SAT_UNSIGNED),
		[SYS_fork] = MAKE_SYS_INFO_STRUCT(fork,),
		[SYS_vfork] = MAKE_SYS_INFO_STRUCT(vfork,),
		[SYS_execve] = MAKE_SYS_INFO_STRUCT(execve, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_ARGV, .arg2 = SAT_ENVP),
		[SYS_exit] = MAKE_SYS_INFO_STRUCT(exit, .arg0 = SAT_INT),
		[SYS_wait4] = MAKE_SYS_INFO_STRUCT(wait4, .arg0 = SAT_PID_T, .arg1 = SAT_PTR, .arg2 = SAT_INT, .arg3 = SAT_PTR),
		[SYS_kill] = MAKE_SYS_INFO_STRUCT(kill, .arg0 = SAT_PID_T, .arg1 = SAT_INT),
		[SYS_uname] = MAKE_SYS_INFO_STRUCT(uname, .arg0 = SAT_PTR),
		[SYS_semget] = MAKE_SYS_INFO_STRUCT(semget, .arg0 = SAT_KEY_T, .arg1 = SAT_INT, .arg2 = SAT_INT),
		[SYS_semop] = MAKE_SYS_INFO_STRUCT(semop, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED),
		[SYS_semctl] = MAKE_SYS_INFO_STRUCT(semctl, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_INT, .arg3 = SAT_UNSIGNED_LONG),
		[SYS_msgsnd] = MAKE_SYS_INFO_STRUCT(msgsnd, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_INT),
		[SYS_msgrcv] = MAKE_SYS_INFO_STRUCT(msgrcv, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_LONG, .arg4 = SAT_INT),
		[SYS_msgctl] = MAKE_SYS_INFO_STRUCT(msgctl, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_PTR),
		[SYS_fcntl] = MAKE_SYS_INFO_STRUCT(fcntl, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_flock] = MAKE_SYS_INFO_STRUCT(flock, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT),
		[SYS_fsync] = MAKE_SYS_INFO_STRUCT(fsync, .arg0 = SAT_UNSIGNED_INT),
		[SYS_fdatasync] = MAKE_SYS_INFO_STRUCT(fdatasync, .arg0 = SAT_UNSIGNED_INT),
		[SYS_truncate] = MAKE_SYS_INFO_STRUCT(truncate, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_LONG),
		[SYS_ftruncate] = MAKE_SYS_INFO_STRUCT(ftruncate, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_LONG),
		[SYS_getdents] = MAKE_SYS_INFO_STRUCT(getdents, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_INT),
		[SYS_getcwd] = MAKE_SYS_INFO_STRUCT(getcwd, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UNSIGNED_LONG),
		[SYS_chdir] = MAKE_SYS_INFO_STRUCT(chdir, .arg0 = SAT_CHAR_PTR),
		[SYS_fchdir] = MAKE_SYS_INFO_STRUCT(fchdir, .arg0 = SAT_UNSIGNED_INT),
		[SYS_rename] = MAKE_SYS_INFO_STRUCT(rename, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR),
		[SYS_mkdir] = MAKE_SYS_INFO_STRUCT(mkdir, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UMODE_T),
		[SYS_rmdir] = MAKE_SYS_INFO_STRUCT(rmdir, .arg0 = SAT_CHAR_PTR),
		[SYS_creat] = MAKE_SYS_INFO_STRUCT(creat, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UMODE_T),
		[SYS_link] = MAKE_SYS_INFO_STRUCT(link, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR),
		[SYS_unlink] = MAKE_SYS_INFO_STRUCT(unlink, .arg0 = SAT_CHAR_PTR),
		[SYS_symlink] = MAKE_SYS_INFO_STRUCT(symlink, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR),
		[SYS_readlink] = MAKE_SYS_INFO_STRUCT(readlink, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT),
		[SYS_chmod] = MAKE_SYS_INFO_STRUCT(chmod, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UMODE_T),
		[SYS_fchmod] = MAKE_SYS_INFO_STRUCT(fchmod, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UMODE_T),
		[SYS_chown] = MAKE_SYS_INFO_STRUCT(chown, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UID_T, .arg2 = SAT_GID_T),
		[SYS_fchown] = MAKE_SYS_INFO_STRUCT(fchown, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UID_T, .arg2 = SAT_GID_T),
		[SYS_lchown] = MAKE_SYS_INFO_STRUCT(lchown, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UID_T, .arg2 = SAT_GID_T),
		[SYS_umask] = MAKE_SYS_INFO_STRUCT(umask, .arg0 = SAT_INT),
		[SYS_gettimeofday] = MAKE_SYS_INFO_STRUCT(gettimeofday, .arg0 = SAT_PTR, .arg1 = SAT_PTR),
		[SYS_getrlimit] = MAKE_SYS_INFO_STRUCT(getrlimit, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_PTR),
		[SYS_getrusage] = MAKE_SYS_INFO_STRUCT(getrusage, .arg0 = SAT_INT, .arg1 = SAT_PTR),
		[SYS_sysinfo] = MAKE_SYS_INFO_STRUCT(sysinfo, .arg0 = SAT_PTR),
		[SYS_times] = MAKE_SYS_INFO_STRUCT(times, .arg0 = SAT_PTR),
		[SYS_ptrace] = MAKE_SYS_INFO_STRUCT(ptrace, .arg0 = SAT_LONG, .arg1 = SAT_LONG, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG),
		[SYS_getuid] = MAKE_SYS_INFO_STRUCT(getuid,),
		[SYS_syslog] = MAKE_SYS_INFO_STRUCT(syslog, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT),
		[SYS_getgid] = MAKE_SYS_INFO_STRUCT(getgid,),
		[SYS_setuid] = MAKE_SYS_INFO_STRUCT(setuid, .arg0 = SAT_UID_T),
		[SYS_setgid] = MAKE_SYS_INFO_STRUCT(setgid, .arg0 = SAT_GID_T),
		[SYS_geteuid] = MAKE_SYS_INFO_STRUCT(geteuid,),
		[SYS_getegid] = MAKE_SYS_INFO_STRUCT(getegid,),
		[SYS_setpgid] = MAKE_SYS_INFO_STRUCT(setpgid, .arg0 = SAT_PID_T, .arg1 = SAT_PID_T),
		[SYS_getppid] = MAKE_SYS_INFO_STRUCT(getppid,),
		[SYS_getpgrp] = MAKE_SYS_INFO_STRUCT(getpgrp,),
		[SYS_setreuid] = MAKE_SYS_INFO_STRUCT(setreuid, .arg0 = SAT_UID_T, .arg1 = SAT_UID_T),
		[SYS_setregid] = MAKE_SYS_INFO_STRUCT(setregid, .arg0 = SAT_GID_T, .arg1 = SAT_GID_T),
		[SYS_getgroups] = MAKE_SYS_INFO_STRUCT(getgroups, .arg0 = SAT_INT, .arg1 = SAT_PTR),
		[SYS_setgroups] = MAKE_SYS_INFO_STRUCT(setgroups, .arg0 = SAT_INT, .arg1 = SAT_PTR),
		[SYS_setresuid] = MAKE_SYS_INFO_STRUCT(setresuid, .arg0 = SAT_UID_T, .arg1 = SAT_UID_T, .arg2 = SAT_UID_T),
		[SYS_getresuid] = MAKE_SYS_INFO_STRUCT(getresuid, .arg0 = SAT_PTR, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_setresgid] = MAKE_SYS_INFO_STRUCT(setresgid, .arg0 = SAT_GID_T, .arg1 = SAT_GID_T, .arg2 = SAT_GID_T),
		[SYS_getresgid] = MAKE_SYS_INFO_STRUCT(getresgid, .arg0 = SAT_PTR, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_getpgid] = MAKE_SYS_INFO_STRUCT(getpgid, .arg0 = SAT_PID_T),
		[SYS_setfsuid] = MAKE_SYS_INFO_STRUCT(setfsuid, .arg0 = SAT_UID_T),
		[SYS_setfsgid] = MAKE_SYS_INFO_STRUCT(setfsgid, .arg0 = SAT_GID_T),
		[SYS_getsid] = MAKE_SYS_INFO_STRUCT(getsid, .arg0 = SAT_PID_T),
		[SYS_capget] = MAKE_SYS_INFO_STRUCT(capget, .arg0 = SAT_CAP_USER_HEADER_T, .arg1 = SAT_CAP_USER_DATA_T),
		[SYS_capset] = MAKE_SYS_INFO_STRUCT(capset, .arg0 = SAT_CAP_USER_HEADER_T, .arg1 = SAT_CONST_CAP_USER_DATA_T),
		[SYS_rt_sigpending] = MAKE_SYS_INFO_STRUCT(rt_sigpending, .arg0 = SAT_PTR, .arg1 = SAT_SIZE_T),
		[SYS_rt_sigtimedwait] = MAKE_SYS_INFO_STRUCT(rt_sigtimedwait, .arg0 = SAT_PTR, .arg1 = SAT_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T),
		[SYS_rt_sigqueueinfo] = MAKE_SYS_INFO_STRUCT(rt_sigqueueinfo, .arg0 = SAT_PID_T, .arg1 = SAT_INT, .arg2 = SAT_PTR),
		[SYS_rt_sigsuspend] = MAKE_SYS_INFO_STRUCT(rt_sigsuspend, .arg0 = SAT_PTR, .arg1 = SAT_SIZE_T),
		[SYS_sigaltstack] = MAKE_SYS_INFO_STRUCT(sigaltstack, .arg0 = SAT_PTR, .arg1 = SAT_PTR),
		[SYS_utime] = MAKE_SYS_INFO_STRUCT(utime, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_PTR),
		[SYS_mknod] = MAKE_SYS_INFO_STRUCT(mknod, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UMODE_T, .arg2 = SAT_UNSIGNED),
		[SYS_uselib] = MAKE_SYS_INFO_STRUCT(uselib, .arg0 = SAT_CHAR_PTR),
		[SYS_personality] = MAKE_SYS_INFO_STRUCT(personality, .arg0 = SAT_UNSIGNED_INT),
		[SYS_ustat] = MAKE_SYS_INFO_STRUCT(ustat, .arg0 = SAT_UNSIGNED, .arg1 = SAT_PTR),
		[SYS_statfs] = MAKE_SYS_INFO_STRUCT(statfs, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_PTR),
		[SYS_fstatfs] = MAKE_SYS_INFO_STRUCT(fstatfs, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_PTR),
		[SYS_sysfs] = MAKE_SYS_INFO_STRUCT(sysfs, .arg0 = SAT_INT, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_getpriority] = MAKE_SYS_INFO_STRUCT(getpriority, .arg0 = SAT_INT, .arg1 = SAT_INT),
		[SYS_setpriority] = MAKE_SYS_INFO_STRUCT(setpriority, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_INT),
		[SYS_sched_setparam] = MAKE_SYS_INFO_STRUCT(sched_setparam, .arg0 = SAT_PID_T, .arg1 = SAT_PTR),
		[SYS_sched_getparam] = MAKE_SYS_INFO_STRUCT(sched_getparam, .arg0 = SAT_PID_T, .arg1 = SAT_PTR),
		[SYS_sched_setscheduler] = MAKE_SYS_INFO_STRUCT(sched_setscheduler, .arg0 = SAT_PID_T, .arg1 = SAT_INT, .arg2 = SAT_PTR),
		[SYS_sched_getscheduler] = MAKE_SYS_INFO_STRUCT(sched_getscheduler, .arg0 = SAT_PID_T),
		[SYS_sched_get_priority_max] = MAKE_SYS_INFO_STRUCT(sched_get_priority_max, .arg0 = SAT_INT),
		[SYS_sched_get_priority_min] = MAKE_SYS_INFO_STRUCT(sched_get_priority_min, .arg0 = SAT_INT),
		[SYS_sched_rr_get_interval] = MAKE_SYS_INFO_STRUCT(sched_rr_get_interval, .arg0 = SAT_PID_T, .arg1 = SAT_PTR),
		[SYS_mlock] = MAKE_SYS_INFO_STRUCT(mlock, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T),
		[SYS_munlock] = MAKE_SYS_INFO_STRUCT(munlock, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T),
		[SYS_mlockall] = MAKE_SYS_INFO_STRUCT(mlockall, .arg0 = SAT_INT),
		[SYS_munlockall] = MAKE_SYS_INFO_STRUCT(munlockall,),
		[SYS_vhangup] = MAKE_SYS_INFO_STRUCT(vhangup,),
		[SYS_modify_ldt] = MAKE_SYS_INFO_STRUCT(modify_ldt, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_pivot_root] = MAKE_SYS_INFO_STRUCT(pivot_root, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR),
		[SYS_prctl] = MAKE_SYS_INFO_STRUCT(prctl, .arg0 = SAT_INT, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_arch_prctl] = MAKE_SYS_INFO_STRUCT(arch_prctl, .arg0 = SAT_INT, .arg1 = SAT_PTR),
		[SYS_adjtimex] = MAKE_SYS_INFO_STRUCT(adjtimex, .arg0 = SAT_PTR),
		[SYS_setrlimit] = MAKE_SYS_INFO_STRUCT(setrlimit, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_PTR),
		[SYS_chroot] = MAKE_SYS_INFO_STRUCT(chroot, .arg0 = SAT_CHAR_PTR),
		[SYS_sync] = MAKE_SYS_INFO_STRUCT(sync,),
		[SYS_acct] = MAKE_SYS_INFO_STRUCT(acct, .arg0 = SAT_CHAR_PTR),
		[SYS_settimeofday] = MAKE_SYS_INFO_STRUCT(settimeofday, .arg0 = SAT_PTR, .arg1 = SAT_PTR),
		[SYS_mount] = MAKE_SYS_INFO_STRUCT(mount, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_CHAR_PTR, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_PTR),
		[SYS_umount2] = MAKE_SYS_INFO_STRUCT(umount2, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_INT),
		[SYS_swapon] = MAKE_SYS_INFO_STRUCT(swapon, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_INT),
		[SYS_swapoff] = MAKE_SYS_INFO_STRUCT(swapoff, .arg0 = SAT_CHAR_PTR),
		[SYS_reboot] = MAKE_SYS_INFO_STRUCT(reboot, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_UNSIGNED_INT, .arg3 = SAT_PTR),
		[SYS_sethostname] = MAKE_SYS_INFO_STRUCT(sethostname, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_INT),
		[SYS_setdomainname] = MAKE_SYS_INFO_STRUCT(setdomainname, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_INT),
		[SYS_iopl] = MAKE_SYS_INFO_STRUCT(iopl, .arg0 = SAT_INT),
		[SYS_ioperm] = MAKE_SYS_INFO_STRUCT(ioperm, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_INT),
		[SYS_init_module] = MAKE_SYS_INFO_STRUCT(init_module, .arg0 = SAT_PTR, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_CHAR_PTR),
		[SYS_delete_module] = MAKE_SYS_INFO_STRUCT(delete_module, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UNSIGNED_INT),
		[SYS_quotactl] = MAKE_SYS_INFO_STRUCT(quotactl, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_QID_T, .arg3 = SAT_PTR),
		[SYS_gettid] = MAKE_SYS_INFO_STRUCT(gettid,),
		[SYS_readahead] = MAKE_SYS_INFO_STRUCT(readahead, .arg0 = SAT_INT, .arg1 = SAT_LOFF_T, .arg2 = SAT_SIZE_T),
		[SYS_setxattr] = MAKE_SYS_INFO_STRUCT(setxattr, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T, .arg4 = SAT_INT),
		[SYS_lsetxattr] = MAKE_SYS_INFO_STRUCT(lsetxattr, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T, .arg4 = SAT_INT),
		[SYS_fsetxattr] = MAKE_SYS_INFO_STRUCT(fsetxattr, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T, .arg4 = SAT_INT),
		[SYS_getxattr] = MAKE_SYS_INFO_STRUCT(getxattr, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T),
		[SYS_lgetxattr] = MAKE_SYS_INFO_STRUCT(lgetxattr, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T),
		[SYS_fgetxattr] = MAKE_SYS_INFO_STRUCT(fgetxattr, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T),
		[SYS_listxattr] = MAKE_SYS_INFO_STRUCT(listxattr, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T),
		[SYS_llistxattr] = MAKE_SYS_INFO_STRUCT(llistxattr, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T),
		[SYS_flistxattr] = MAKE_SYS_INFO_STRUCT(flistxattr, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T),
		[SYS_removexattr] = MAKE_SYS_INFO_STRUCT(removexattr, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR),
		[SYS_lremovexattr] = MAKE_SYS_INFO_STRUCT(lremovexattr, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR),
		[SYS_fremovexattr] = MAKE_SYS_INFO_STRUCT(fremovexattr, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR),
		[SYS_tkill] = MAKE_SYS_INFO_STRUCT(tkill, .arg0 = SAT_PID_T, .arg1 = SAT_INT),
		[SYS_time] = MAKE_SYS_INFO_STRUCT(time, .arg0 = SAT_PTR),
		[SYS_futex] = MAKE_SYS_INFO_STRUCT(futex, .arg0 = SAT_PTR, .arg1 = SAT_INT, .arg2 = SAT_U32, .arg3 = SAT_PTR, .arg4 = SAT_PTR, .arg5 = SAT_U32),
		[SYS_sched_setaffinity] = MAKE_SYS_INFO_STRUCT(sched_setaffinity, .arg0 = SAT_PID_T, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_PTR),
		[SYS_sched_getaffinity] = MAKE_SYS_INFO_STRUCT(sched_getaffinity, .arg0 = SAT_PID_T, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_PTR),
		[SYS_set_thread_area] = MAKE_SYS_INFO_STRUCT(set_thread_area, .arg0 = SAT_PTR),
		[SYS_io_setup] = MAKE_SYS_INFO_STRUCT(io_setup, .arg0 = SAT_UNSIGNED, .arg1 = SAT_PTR),
		[SYS_io_destroy] = MAKE_SYS_INFO_STRUCT(io_destroy, .arg0 = SAT_AIO_CONTEXT_T),
		[SYS_io_getevents] = MAKE_SYS_INFO_STRUCT(io_getevents, .arg0 = SAT_AIO_CONTEXT_T, .arg1 = SAT_LONG, .arg2 = SAT_LONG, .arg3 = SAT_PTR, .arg4 = SAT_PTR),
		[SYS_io_submit] = MAKE_SYS_INFO_STRUCT(io_submit, .arg0 = SAT_AIO_CONTEXT_T, .arg1 = SAT_LONG, .arg2 = SAT_PTR),
		[SYS_io_cancel] = MAKE_SYS_INFO_STRUCT(io_cancel, .arg0 = SAT_AIO_CONTEXT_T, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_get_thread_area] = MAKE_SYS_INFO_STRUCT(get_thread_area, .arg0 = SAT_PTR),
		[SYS_lookup_dcookie] = MAKE_SYS_INFO_STRUCT(lookup_dcookie, .arg0 = SAT_U64, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T),
		[SYS_epoll_create] = MAKE_SYS_INFO_STRUCT(epoll_create, .arg0 = SAT_INT),
		[SYS_remap_file_pages] = MAKE_SYS_INFO_STRUCT(remap_file_pages, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_getdents64] = MAKE_SYS_INFO_STRUCT(getdents64, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_INT),
		[SYS_set_tid_address] = MAKE_SYS_INFO_STRUCT(set_tid_address, .arg0 = SAT_PTR),
		[SYS_restart_syscall] = MAKE_SYS_INFO_STRUCT(restart_syscall,),
		[SYS_semtimedop] = MAKE_SYS_INFO_STRUCT(semtimedop, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED, .arg3 = SAT_PTR),
		[SYS_fadvise64] = MAKE_SYS_INFO_STRUCT(fadvise64, .arg0 = SAT_INT, .arg1 = SAT_LOFF_T, .arg2 = SAT_SIZE_T, .arg3 = SAT_INT),
		[SYS_timer_create] = MAKE_SYS_INFO_STRUCT(timer_create, .arg0 = SAT_CLOCKID_T, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_timer_settime] = MAKE_SYS_INFO_STRUCT(timer_settime, .arg0 = SAT_TIMER_T, .arg1 = SAT_INT, .arg2 = SAT_PTR, .arg3 = SAT_PTR),
		[SYS_timer_gettime] = MAKE_SYS_INFO_STRUCT(timer_gettime, .arg0 = SAT_TIMER_T, .arg1 = SAT_PTR),
		[SYS_timer_getoverrun] = MAKE_SYS_INFO_STRUCT(timer_getoverrun, .arg0 = SAT_TIMER_T),
		[SYS_timer_delete] = MAKE_SYS_INFO_STRUCT(timer_delete, .arg0 = SAT_TIMER_T),
		[SYS_clock_settime] = MAKE_SYS_INFO_STRUCT(clock_settime, .arg0 = SAT_CLOCKID_T, .arg1 = SAT_PTR),
		[SYS_clock_gettime] = MAKE_SYS_INFO_STRUCT(clock_gettime, .arg0 = SAT_CLOCKID_T, .arg1 = SAT_PTR),
		[SYS_clock_getres] = MAKE_SYS_INFO_STRUCT(clock_getres, .arg0 = SAT_CLOCKID_T, .arg1 = SAT_PTR),
		[SYS_clock_nanosleep] = MAKE_SYS_INFO_STRUCT(clock_nanosleep, .arg0 = SAT_CLOCKID_T, .arg1 = SAT_INT, .arg2 = SAT_PTR, .arg3 = SAT_PTR),
		[SYS_exit_group] = MAKE_SYS_INFO_STRUCT(exit_group, .arg0 = SAT_INT),
		[SYS_epoll_wait] = MAKE_SYS_INFO_STRUCT(epoll_wait, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_INT, .arg3 = SAT_INT),
		[SYS_epoll_ctl] = MAKE_SYS_INFO_STRUCT(epoll_ctl, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_INT, .arg3 = SAT_PTR),
		[SYS_tgkill] = MAKE_SYS_INFO_STRUCT(tgkill, .arg0 = SAT_PID_T, .arg1 = SAT_PID_T, .arg2 = SAT_INT),
		[SYS_utimes] = MAKE_SYS_INFO_STRUCT(utimes, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_PTR),
		[SYS_mbind] = MAKE_SYS_INFO_STRUCT(mbind, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_PTR, .arg4 = SAT_UNSIGNED_LONG, .arg5 = SAT_UNSIGNED),
		[SYS_set_mempolicy] = MAKE_SYS_INFO_STRUCT(set_mempolicy, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_get_mempolicy] = MAKE_SYS_INFO_STRUCT(get_mempolicy, .arg0 = SAT_PTR, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_mq_open] = MAKE_SYS_INFO_STRUCT(mq_open, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_INT, .arg2 = SAT_UMODE_T, .arg3 = SAT_PTR),
		[SYS_mq_unlink] = MAKE_SYS_INFO_STRUCT(mq_unlink, .arg0 = SAT_CHAR_PTR),
		[SYS_mq_timedsend] = MAKE_SYS_INFO_STRUCT(mq_timedsend, .arg0 = SAT_MQD_T, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_UNSIGNED_INT, .arg4 = SAT_PTR),
		[SYS_mq_timedreceive] = MAKE_SYS_INFO_STRUCT(mq_timedreceive, .arg0 = SAT_MQD_T, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_PTR, .arg4 = SAT_PTR),
		[SYS_mq_notify] = MAKE_SYS_INFO_STRUCT(mq_notify, .arg0 = SAT_MQD_T, .arg1 = SAT_PTR),
		[SYS_mq_getsetattr] = MAKE_SYS_INFO_STRUCT(mq_getsetattr, .arg0 = SAT_MQD_T, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_kexec_load] = MAKE_SYS_INFO_STRUCT(kexec_load, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_PTR, .arg3 = SAT_UNSIGNED_LONG),
		[SYS_waitid] = MAKE_SYS_INFO_STRUCT(waitid, .arg0 = SAT_INT, .arg1 = SAT_PID_T, .arg2 = SAT_PTR, .arg3 = SAT_INT, .arg4 = SAT_PTR),
		[SYS_add_key] = MAKE_SYS_INFO_STRUCT(add_key, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T, .arg4 = SAT_KEY_SERIAL_T),
		[SYS_request_key] = MAKE_SYS_INFO_STRUCT(request_key, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_CHAR_PTR, .arg3 = SAT_KEY_SERIAL_T),
		[SYS_keyctl] = MAKE_SYS_INFO_STRUCT(keyctl, .arg0 = SAT_INT, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_ioprio_set] = MAKE_SYS_INFO_STRUCT(ioprio_set, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_INT),
		[SYS_ioprio_get] = MAKE_SYS_INFO_STRUCT(ioprio_get, .arg0 = SAT_INT, .arg1 = SAT_INT),
		[SYS_inotify_init] = MAKE_SYS_INFO_STRUCT(inotify_init,),
		[SYS_inotify_add_watch] = MAKE_SYS_INFO_STRUCT(inotify_add_watch, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_U32),
		[SYS_inotify_rm_watch] = MAKE_SYS_INFO_STRUCT(inotify_rm_watch, .arg0 = SAT_INT, .arg1 = SAT__S32),
		[SYS_migrate_pages] = MAKE_SYS_INFO_STRUCT(migrate_pages, .arg0 = SAT_PID_T, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_PTR, .arg3 = SAT_PTR),
		[SYS_openat] = MAKE_SYS_INFO_STRUCT(openat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT, .arg3 = SAT_UMODE_T),
		[SYS_mkdirat] = MAKE_SYS_INFO_STRUCT(mkdirat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_UMODE_T),
		[SYS_mknodat] = MAKE_SYS_INFO_STRUCT(mknodat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_UMODE_T, .arg3 = SAT_UNSIGNED),
		[SYS_fchownat] = MAKE_SYS_INFO_STRUCT(fchownat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_UID_T, .arg3 = SAT_GID_T, .arg4 = SAT_INT),
		[SYS_futimesat] = MAKE_SYS_INFO_STRUCT(futimesat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR),
		[SYS_newfstatat] = MAKE_SYS_INFO_STRUCT(newfstatat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_INT),
		[SYS_unlinkat] = MAKE_SYS_INFO_STRUCT(unlinkat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT),
		[SYS_renameat] = MAKE_SYS_INFO_STRUCT(renameat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT, .arg3 = SAT_CHAR_PTR),
		[SYS_linkat] = MAKE_SYS_INFO_STRUCT(linkat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT, .arg3 = SAT_CHAR_PTR, .arg4 = SAT_INT),
		[SYS_symlinkat] = MAKE_SYS_INFO_STRUCT(symlinkat, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_INT, .arg2 = SAT_CHAR_PTR),
		[SYS_readlinkat] = MAKE_SYS_INFO_STRUCT(readlinkat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_CHAR_PTR, .arg3 = SAT_INT),
		[SYS_fchmodat] = MAKE_SYS_INFO_STRUCT(fchmodat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_UMODE_T),
		[SYS_faccessat] = MAKE_SYS_INFO_STRUCT(faccessat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT),
		[SYS_pselect6] = MAKE_SYS_INFO_STRUCT(pselect6, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR, .arg3 = SAT_PTR, .arg4 = SAT_PTR, .arg5 = SAT_PTR),
		[SYS_ppoll] = MAKE_SYS_INFO_STRUCT(ppoll, .arg0 = SAT_PTR, .arg1 = SAT_UNSIGNED, .arg2 = SAT_PTR, .arg3 = SAT_PTR, .arg4 = SAT_SIZE_T),
		[SYS_unshare] = MAKE_SYS_INFO_STRUCT(unshare, .arg0 = SAT_UNSIGNED_LONG),
		[SYS_set_robust_list] = MAKE_SYS_INFO_STRUCT(set_robust_list, .arg0 = SAT_PTR, .arg1 = SAT_SIZE_T),
		[SYS_get_robust_list] = MAKE_SYS_INFO_STRUCT(get_robust_list, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_splice] = MAKE_SYS_INFO_STRUCT(splice, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_INT, .arg3 = SAT_PTR, .arg4 = SAT_SIZE_T, .arg5 = SAT_UNSIGNED_INT),
		[SYS_tee] = MAKE_SYS_INFO_STRUCT(tee, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_SIZE_T, .arg3 = SAT_UNSIGNED_INT),
		[SYS_sync_file_range] = MAKE_SYS_INFO_STRUCT(sync_file_range, .arg0 = SAT_INT, .arg1 = SAT_LOFF_T, .arg2 = SAT_LOFF_T, .arg3 = SAT_UNSIGNED_INT),
		[SYS_vmsplice] = MAKE_SYS_INFO_STRUCT(vmsplice, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_INT),
		[SYS_move_pages] = MAKE_SYS_INFO_STRUCT(move_pages, .arg0 = SAT_PID_T, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_PTR, .arg3 = SAT_PTR, .arg4 = SAT_PTR, .arg5 = SAT_INT),
		[SYS_utimensat] = MAKE_SYS_INFO_STRUCT(utimensat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_INT),
		[SYS_epoll_pwait] = MAKE_SYS_INFO_STRUCT(epoll_pwait, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_INT, .arg3 = SAT_INT, .arg4 = SAT_PTR, .arg5 = SAT_SIZE_T),
		[SYS_signalfd] = MAKE_SYS_INFO_STRUCT(signalfd, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_SIZE_T),
		[SYS_timerfd_create] = MAKE_SYS_INFO_STRUCT(timerfd_create, .arg0 = SAT_INT, .arg1 = SAT_INT),
		[SYS_eventfd] = MAKE_SYS_INFO_STRUCT(eventfd, .arg0 = SAT_UNSIGNED_INT),
		[SYS_fallocate] = MAKE_SYS_INFO_STRUCT(fallocate, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_LOFF_T, .arg3 = SAT_LOFF_T),
		[SYS_timerfd_settime] = MAKE_SYS_INFO_STRUCT(timerfd_settime, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_PTR, .arg3 = SAT_PTR),
		[SYS_timerfd_gettime] = MAKE_SYS_INFO_STRUCT(timerfd_gettime, .arg0 = SAT_INT, .arg1 = SAT_PTR),
		[SYS_accept4] = MAKE_SYS_INFO_STRUCT(accept4, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR, .arg3 = SAT_INT),
		[SYS_signalfd4] = MAKE_SYS_INFO_STRUCT(signalfd4, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_INT),
		[SYS_eventfd2] = MAKE_SYS_INFO_STRUCT(eventfd2, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_INT),
		[SYS_epoll_create1] = MAKE_SYS_INFO_STRUCT(epoll_create1, .arg0 = SAT_INT),
		[SYS_dup3] = MAKE_SYS_INFO_STRUCT(dup3, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_INT),
		[SYS_pipe2] = MAKE_SYS_INFO_STRUCT(pipe2, .arg0 = SAT_PTR, .arg1 = SAT_INT),
		[SYS_inotify_init1] = MAKE_SYS_INFO_STRUCT(inotify_init1, .arg0 = SAT_INT),
		[SYS_preadv] = MAKE_SYS_INFO_STRUCT(preadv, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_pwritev] = MAKE_SYS_INFO_STRUCT(pwritev, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_rt_tgsigqueueinfo] = MAKE_SYS_INFO_STRUCT(rt_tgsigqueueinfo, .arg0 = SAT_PID_T, .arg1 = SAT_PID_T, .arg2 = SAT_INT, .arg3 = SAT_PTR),
		[SYS_perf_event_open] = MAKE_SYS_INFO_STRUCT(perf_event_open, .arg0 = SAT_PTR, .arg1 = SAT_PID_T, .arg2 = SAT_INT, .arg3 = SAT_INT, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_recvmmsg] = MAKE_SYS_INFO_STRUCT(recvmmsg, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_INT, .arg3 = SAT_UNSIGNED, .arg4 = SAT_PTR),
		[SYS_fanotify_init] = MAKE_SYS_INFO_STRUCT(fanotify_init, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT),
		[SYS_fanotify_mark] = MAKE_SYS_INFO_STRUCT(fanotify_mark, .arg0 = SAT_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_U64, .arg3 = SAT_INT, .arg4 = SAT_CHAR_PTR),
		[SYS_prlimit64] = MAKE_SYS_INFO_STRUCT(prlimit64, .arg0 = SAT_PID_T, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_PTR, .arg3 = SAT_PTR),
		[SYS_name_to_handle_at] = MAKE_SYS_INFO_STRUCT(name_to_handle_at, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_PTR, .arg4 = SAT_INT),
		[SYS_open_by_handle_at] = MAKE_SYS_INFO_STRUCT(open_by_handle_at, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_INT),
		[SYS_clock_adjtime] = MAKE_SYS_INFO_STRUCT(clock_adjtime, .arg0 = SAT_CLOCKID_T, .arg1 = SAT_PTR),
		[SYS_syncfs] = MAKE_SYS_INFO_STRUCT(syncfs, .arg0 = SAT_INT),
		[SYS_sendmmsg] = MAKE_SYS_INFO_STRUCT(sendmmsg, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_INT, .arg3 = SAT_UNSIGNED),
		[SYS_setns] = MAKE_SYS_INFO_STRUCT(setns, .arg0 = SAT_INT, .arg1 = SAT_INT),
		[SYS_getcpu] = MAKE_SYS_INFO_STRUCT(getcpu, .arg0 = SAT_PTR, .arg1 = SAT_PTR, .arg2 = SAT_PTR),
		[SYS_process_vm_readv] = MAKE_SYS_INFO_STRUCT(process_vm_readv, .arg0 = SAT_PID_T, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_PTR, .arg4 = SAT_UNSIGNED_LONG, .arg5 = SAT_UNSIGNED_LONG),
		[SYS_process_vm_writev] = MAKE_SYS_INFO_STRUCT(process_vm_writev, .arg0 = SAT_PID_T, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_PTR, .arg4 = SAT_UNSIGNED_LONG, .arg5 = SAT_UNSIGNED_LONG),
		[SYS_kcmp] = MAKE_SYS_INFO_STRUCT(kcmp, .arg0 = SAT_PID_T, .arg1 = SAT_PID_T, .arg2 = SAT_INT, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_finit_module] = MAKE_SYS_INFO_STRUCT(finit_module, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT),
		[SYS_sched_setattr] = MAKE_SYS_INFO_STRUCT(sched_setattr, .arg0 = SAT_PID_T, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_INT),
		[SYS_sched_getattr] = MAKE_SYS_INFO_STRUCT(sched_getattr, .arg0 = SAT_PID_T, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_INT, .arg3 = SAT_UNSIGNED_INT),
		[SYS_renameat2] = MAKE_SYS_INFO_STRUCT(renameat2, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT, .arg3 = SAT_CHAR_PTR, .arg4 = SAT_UNSIGNED_INT),
		[SYS_seccomp] = MAKE_SYS_INFO_STRUCT(seccomp, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_PTR),
		[SYS_getrandom] = MAKE_SYS_INFO_STRUCT(getrandom, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_SIZE_T, .arg2 = SAT_UNSIGNED_INT),
		[SYS_memfd_create] = MAKE_SYS_INFO_STRUCT(memfd_create, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UNSIGNED_INT),
		[SYS_kexec_file_load] = MAKE_SYS_INFO_STRUCT(kexec_file_load, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_CHAR_PTR, .arg4 = SAT_UNSIGNED_LONG),
		[SYS_bpf] = MAKE_SYS_INFO_STRUCT(bpf, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_INT),
		[SYS_execveat] = MAKE_SYS_INFO_STRUCT(execveat, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_ARGV, .arg3 = SAT_ENVP, .arg4 = SAT_INT),
		[SYS_userfaultfd] = MAKE_SYS_INFO_STRUCT(userfaultfd, .arg0 = SAT_INT),
		[SYS_membarrier] = MAKE_SYS_INFO_STRUCT(membarrier, .arg0 = SAT_INT, .arg1 = SAT_INT),
		[SYS_mlock2] = MAKE_SYS_INFO_STRUCT(mlock2, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T, .arg2 = SAT_INT),
		[SYS_copy_file_range] = MAKE_SYS_INFO_STRUCT(copy_file_range, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_INT, .arg3 = SAT_PTR, .arg4 = SAT_SIZE_T, .arg5 = SAT_UNSIGNED_INT),
		[SYS_preadv2] = MAKE_SYS_INFO_STRUCT(preadv2, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG, .arg5 = SAT_RWF_T),
		[SYS_pwritev2] = MAKE_SYS_INFO_STRUCT(pwritev2, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_PTR, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG, .arg4 = SAT_UNSIGNED_LONG, .arg5 = SAT_RWF_T),
		[SYS_pkey_mprotect] = MAKE_SYS_INFO_STRUCT(pkey_mprotect, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_SIZE_T, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_INT),
		[SYS_pkey_alloc] = MAKE_SYS_INFO_STRUCT(pkey_alloc, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_UNSIGNED_LONG),
		[SYS_pkey_free] = MAKE_SYS_INFO_STRUCT(pkey_free, .arg0 = SAT_INT),
		[SYS_statx] = MAKE_SYS_INFO_STRUCT(statx, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_UNSIGNED, .arg3 = SAT_UNSIGNED, .arg4 = SAT_PTR),
		[SYS_io_pgetevents] = MAKE_SYS_INFO_STRUCT(io_pgetevents, .arg0 = SAT_AIO_CONTEXT_T, .arg1 = SAT_LONG, .arg2 = SAT_LONG, .arg3 = SAT_PTR, .arg4 = SAT_PTR, .arg5 = SAT_PTR),
		[SYS_rseq] = MAKE_SYS_INFO_STRUCT(rseq, .arg0 = SAT_PTR, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_INT, .arg3 = SAT_UNSIGNED_INT),
		[SYS_pidfd_send_signal] = MAKE_SYS_INFO_STRUCT(pidfd_send_signal, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_PTR, .arg3 = SAT_UNSIGNED_INT),
		[SYS_io_uring_enter] = MAKE_SYS_INFO_STRUCT(io_uring_enter, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_UNSIGNED_INT, .arg3 = SAT_UNSIGNED_INT, .arg4 = SAT_PTR, .arg5 = SAT_SIZE_T),
		[SYS_io_uring_setup] = MAKE_SYS_INFO_STRUCT(io_uring_setup, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_PTR),
		[SYS_io_uring_register] = MAKE_SYS_INFO_STRUCT(io_uring_register, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_PTR, .arg3 = SAT_UNSIGNED_INT),
		[SYS_open_tree] = MAKE_SYS_INFO_STRUCT(open_tree, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_UNSIGNED_INT),
		[SYS_move_mount] = MAKE_SYS_INFO_STRUCT(move_mount, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT, .arg3 = SAT_CHAR_PTR, .arg4 = SAT_UNSIGNED_INT),
		[SYS_fsopen] = MAKE_SYS_INFO_STRUCT(fsopen, .arg0 = SAT_CHAR_PTR, .arg1 = SAT_UNSIGNED_INT),
		[SYS_fsconfig] = MAKE_SYS_INFO_STRUCT(fsconfig, .arg0 = SAT_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_CHAR_PTR, .arg3 = SAT_CHAR_PTR, .arg4 = SAT_INT),
		[SYS_fsmount] = MAKE_SYS_INFO_STRUCT(fsmount, .arg0 = SAT_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_UNSIGNED_LONG),
		[SYS_fspick] = MAKE_SYS_INFO_STRUCT(fspick, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_UNSIGNED_INT),
		[SYS_pidfd_open] = MAKE_SYS_INFO_STRUCT(pidfd_open, .arg0 = SAT_PID_T, .arg1 = SAT_UNSIGNED_INT),
		[SYS_clone3] = MAKE_SYS_INFO_STRUCT(clone3, .arg0 = SAT_PTR, .arg1 = SAT_SIZE_T),
		[SYS_close_range] = MAKE_SYS_INFO_STRUCT(close_range, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_UNSIGNED_INT),
		[SYS_openat2] = MAKE_SYS_INFO_STRUCT(openat2, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_PTR, .arg3 = SAT_SIZE_T),
		[SYS_pidfd_getfd] = MAKE_SYS_INFO_STRUCT(pidfd_getfd, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_UNSIGNED_INT),
		[SYS_faccessat2] = MAKE_SYS_INFO_STRUCT(faccessat2, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_INT, .arg3 = SAT_INT),
		[SYS_process_madvise] = MAKE_SYS_INFO_STRUCT(process_madvise, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_SIZE_T, .arg3 = SAT_INT, .arg4 = SAT_UNSIGNED_INT),
		[SYS_epoll_pwait2] = MAKE_SYS_INFO_STRUCT(epoll_pwait2, .arg0 = SAT_INT, .arg1 = SAT_PTR, .arg2 = SAT_INT, .arg3 = SAT_PTR, .arg4 = SAT_PTR, .arg5 = SAT_SIZE_T),
		[SYS_mount_setattr] = MAKE_SYS_INFO_STRUCT(mount_setattr, .arg0 = SAT_INT, .arg1 = SAT_CHAR_PTR, .arg2 = SAT_UNSIGNED_INT, .arg3 = SAT_PTR, .arg4 = SAT_SIZE_T),
		[SYS_quotactl_fd] = MAKE_SYS_INFO_STRUCT(quotactl_fd, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_CHAR_PTR, .arg3 = SAT_INT, .arg4 = SAT_PTR),
		[SYS_landlock_create_ruleset] = MAKE_SYS_INFO_STRUCT(landlock_create_ruleset, .arg0 = SAT_PTR, .arg1 = SAT_SIZE_T, .arg2 = SAT_UNSIGNED_INT),
		[SYS_landlock_add_rule] = MAKE_SYS_INFO_STRUCT(landlock_add_rule, .arg0 = SAT_INT, .arg1 = SAT_INT, .arg2 = SAT_PTR, .arg3 = SAT_UNSIGNED_INT),
		[SYS_landlock_restrict_self] = MAKE_SYS_INFO_STRUCT(landlock_restrict_self, .arg0 = SAT_INT, .arg1 = SAT_UNSIGNED_INT),
		[SYS_memfd_secret] = MAKE_SYS_INFO_STRUCT(memfd_secret, .arg0 = SAT_UNSIGNED_INT),
		[SYS_process_mrelease] = MAKE_SYS_INFO_STRUCT(process_mrelease, .arg0 = SAT_INT, .arg1 = SAT_UNSIGNED_INT),
		[SYS_futex_waitv] = MAKE_SYS_INFO_STRUCT(futex_waitv, .arg0 = SAT_PTR, .arg1 = SAT_UNSIGNED_INT, .arg2 = SAT_UNSIGNED_INT, .arg3 = SAT_PTR, .arg4 = SAT_CLOCKID_T),
		[SYS_set_mempolicy_home_node] = MAKE_SYS_INFO_STRUCT(set_mempolicy_home_node, .arg0 = SAT_UNSIGNED_LONG, .arg1 = SAT_UNSIGNED_LONG, .arg2 = SAT_UNSIGNED_LONG, .arg3 = SAT_UNSIGNED_LONG),
		[SYS_cachestat] = MAKE_SYS_INFO_STRUCT(cachestat, .arg0 = SAT_UNSIGNED_INT, .arg1 = SAT_PTR, .arg2 = SAT_PTR, .arg3 = SAT_UNSIGNED_INT),
	};
	return info_table[syscall_number];
}

#define CHECK_ARG(N) if (args.arg##N == SAT_NO_ARG) return N;

int get_num_arg(u64 syscall_number)
{
    t_syscall_args args = get_syscall_info(syscall_number).args;
    CHECK_ARG(0);
    CHECK_ARG(1);
    CHECK_ARG(2);
    CHECK_ARG(3);
    CHECK_ARG(4);
    CHECK_ARG(5);
	return 6;
}
