/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   get_printer_func.c                                 :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ellanglo <ellanglo@42angouleme.fr>         +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/08/31 19:10:13 by ellanglo          #+#    #+#             */
/*   Updated: 2025/09/01 01:14:53 by wirare           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
#include <ft_strace.h>
#include <stdio.h>

void print(t_syscall_arg_type type, u64 data)
{
	static const pfn_printer printer_table[] = 
	{
		DEFINE_PRINTER(SAT_VA_ARGS)
		DEFINE_PRINTER(SAT_STRUCT_KEXEC_SEGMENT_PTR)
		DEFINE_PRINTER(SAT_INT)
		DEFINE_PRINTER(SAT_STRUCT_SIGALTSTACK_PTR)
		DEFINE_PRINTER(SAT_UNION_BPF_ATTR_PTR)
		DEFINE_PRINTER(SAT_STRUCT_USER_MSGHDR_PTR)
		DEFINE_PRINTER(SAT_CHAR_PTR)
		DEFINE_PRINTER(SAT_STRUCT__KERNEL_ITIMERSPEC_PTR)
		DEFINE_PRINTER(SAT_CAP_USER_HEADER_T)
		DEFINE_PRINTER(SAT_CONST_CAP_USER_DATA_T)
		DEFINE_PRINTER(SAT_STRUCT_IOCB_PTR)
		DEFINE_PRINTER(SAT_MQD_T)
		DEFINE_PRINTER(SAT_SIZE_T)
		DEFINE_PRINTER(SAT_OFF_T)
		DEFINE_PRINTER(SAT_STRUCT_PERF_EVENT_ATTR_PTR)
		DEFINE_PRINTER(SAT_SIGSET_T_PTR)
		DEFINE_PRINTER(SAT_STRUCT_OLD_UTSNAME_PTR)
		DEFINE_PRINTER(SAT_KEY_T)
		DEFINE_PRINTER(SAT_UNSIGNED_INT)
		DEFINE_PRINTER(SAT_INT_PTR)
		DEFINE_PRINTER(SAT_LOFF_T_PTR)
		DEFINE_PRINTER(SAT_UNSIGNED_INT_PTR)
		DEFINE_PRINTER(SAT_TIME_T_PTR)
		DEFINE_PRINTER(SAT_STRUCT_SCHED_PARAM_PTR)
		DEFINE_PRINTER(SAT_AIO_CONTEXT_T)
		DEFINE_PRINTER(SAT_OFF_T_PTR)
		DEFINE_PRINTER(SAT_QID_T)
		DEFINE_PRINTER(SAT_STRUCT__KERNEL_TIMESPEC_PTR)
		DEFINE_PRINTER(SAT_STRUCT__KERNEL_TIMEX_PTR)
		DEFINE_PRINTER(SAT_STRUCT_MQ_ATTR_PTR)
		DEFINE_PRINTER(SAT_STRUCT_RLIMIT64_PTR)
		DEFINE_PRINTER(SAT_STRUCT_STATFS_PTR)
		DEFINE_PRINTER(SAT_CONST_STRUCT__KERNEL_ITIMERSPEC_PTR)
		DEFINE_PRINTER(SAT_KEY_SERIAL_T)
		DEFINE_PRINTER(SAT_TIMER_T)
		DEFINE_PRINTER(SAT_STRUCT_RUSAGE_PTR)
		DEFINE_PRINTER(SAT_UNSIGNED)
		DEFINE_PRINTER(SAT_GID_T)
		DEFINE_PRINTER(SAT_CONST_STRUCT_SIGALTSTACK_PTR)
		DEFINE_PRINTER(SAT_STRUCT_EPOLL_EVENT_PTR)
		DEFINE_PRINTER(SAT_SIZE_T_PTR)
		DEFINE_PRINTER(SAT_STRUCT_GETCPU_CACHE_PTR)
		DEFINE_PRINTER(SAT_LONG)
		DEFINE_PRINTER(SAT_U32_PTR)
		DEFINE_PRINTER(SAT_STRUCT_FILE_HANDLE_PTR)
		DEFINE_PRINTER(SAT_STRUCT_RLIMIT_PTR)
		DEFINE_PRINTER(SAT_CONST_STRUCT_MQ_ATTR_PTR)
		DEFINE_PRINTER(SAT_STRUCT_MSQID_DS_PTR)
		DEFINE_PRINTER(SAT_STRUCT_IO_EVENT_PTR)
		DEFINE_PRINTER(SAT_STRUCT_SYSINFO_PTR)
		DEFINE_PRINTER(SAT_STRUCT_TIMEZONE_PTR)
		DEFINE_PRINTER(SAT_STRUCT_SOCKADDR_PTR)
		DEFINE_PRINTER(SAT_UID_T)
		DEFINE_PRINTER(SAT_CONST_STRUCT_RLIMIT64_PTR)
		DEFINE_PRINTER(SAT_CONST_VOID_PTR_PTR)
		DEFINE_PRINTER(SAT_CONST_VOID_PTR)
		DEFINE_PRINTER(SAT_CAP_USER_DATA_T)
		DEFINE_PRINTER(SAT_STRUCT_USTAT_PTR)
		DEFINE_PRINTER(SAT_STRUCT_ROBUST_LIST_HEAD_PTR)
		DEFINE_PRINTER(SAT_CONST_SIGSET_T_PTR)
		DEFINE_PRINTER(SAT_STRUCT_UTIMBUF_PTR)
		DEFINE_PRINTER(SAT_CONST_STRUCT_SIGEVENT_PTR)
		DEFINE_PRINTER(SAT_CLOCKID_T)
		DEFINE_PRINTER(SAT_TIMER_T_PTR_)
		DEFINE_PRINTER(SAT_CONST_STRUCT_IOVEC_PTR)
		DEFINE_PRINTER(SAT_STRUCT_ITIMERVAL_PTR)
		DEFINE_PRINTER(SAT_CONST_STRUCT__KERNEL_TIMESPEC_PTR)
		DEFINE_PRINTER(SAT_UNSIGNED_PTR)
		DEFINE_PRINTER(SAT_CONST_CHAR_PTR_)
		DEFINE_PRINTER(SAT_STRUCT_STATX_PTR)
		DEFINE_PRINTER(SAT_FD_SET_PTR)
		DEFINE_PRINTER(SAT_STRUCT_LINUX_DIRENT_PTR)
		DEFINE_PRINTER(SAT_CONST_INT_PTR)
		DEFINE_PRINTER(SAT_UNSIGNED_LONG)
		DEFINE_PRINTER(SAT_STRUCT_SIGEVENT_PTR)
		DEFINE_PRINTER(SAT__S32)
		DEFINE_PRINTER(SAT_STRUCT_STAT_PTR)
		DEFINE_PRINTER(SAT_GID_T_PTR)
		DEFINE_PRINTER(SAT_U64)
		DEFINE_PRINTER(SAT_SIGINFO_T_PTR)
		DEFINE_PRINTER(SAT_STRUCT_TMS_PTR)
		DEFINE_PRINTER(SAT_U32)
		DEFINE_PRINTER(SAT_STRUCT_SEMBUF_PTR)
		DEFINE_PRINTER(SAT_STRUCT_SHMID_DS_PTR)
		DEFINE_PRINTER(SAT_STRUCT_TIMEVAL_PTR)
		DEFINE_PRINTER(SAT_STRUCT__OLD_KERNEL_STAT_PTR)
		DEFINE_PRINTER(SAT_STRUCT_LINUX_DIRENT64_PTR)
		DEFINE_PRINTER(SAT_CONST_CHAR_PTR_CONST_PTR)
		DEFINE_PRINTER(SAT_STRUCT_SIGACTION_PTR)
		DEFINE_PRINTER(SAT_AIO_CONTEXT_T_PTR)
		DEFINE_PRINTER(SAT_LOFF_T)
		DEFINE_PRINTER(SAT_STRUCT_MSGBUF_PTR)
		DEFINE_PRINTER(SAT_STRUCT_POLLFD_PTR)
		DEFINE_PRINTER(SAT_CONST_CHAR_PTR)
		DEFINE_PRINTER(SAT_PID_T)
		DEFINE_PRINTER(SAT_STRUCT_MMSGHDR_PTR)
		DEFINE_PRINTER(SAT_RWF_T)
		DEFINE_PRINTER(SAT_UNSIGNED_CHAR_PTR_)
		DEFINE_PRINTER(SAT_STRUCT_SCHED_ATTR_PTR)
		DEFINE_PRINTER(SAT_CONST_UNSIGNED_LONG_PTR)
		DEFINE_PRINTER(SAT_CONST_STRUCT_SIGACTION_PTR)
		DEFINE_PRINTER(SAT_STRUCT_IOCB_PTR_PTR)
		DEFINE_PRINTER(SAT_UMODE_T)
		DEFINE_PRINTER(SAT_STRUCT_ROBUST_LIST_HEAD_PTR_PTR)
		DEFINE_PRINTER(SAT_UID_T_PTR)
		DEFINE_PRINTER(SAT_VOID_PTR)
		DEFINE_PRINTER(SAT_STRUCT_SIGINFO_PTR)
DEFINE_PRINTER(SAT_UNSIGNED_LONG_PTR)
		DEFINE_PRINTER(SAT_STRUCT_USER_DESC_PTR)
		DEFINE_PRINTER(SAT_NO_ARG)
		DEFINE_PRINTER(SAT_CONST_STRUCT_TIMESPEC_PTR)
		DEFINE_PRINTER(SAT_STRUCT_RSEQ_PTR)
		DEFINE_PRINTER(SAT_STRUCT_IO_URING_PARAMS_PTR)
		DEFINE_PRINTER(SAT_STRUCT_CLONE_ARGS_PTR)
		DEFINE_PRINTER(SAT_STRUCT_OPEN_HOW_PTR)
		DEFINE_PRINTER(SAT_STRUCT_IOVEC_PTR)
		DEFINE_PRINTER(SAT_STRUCT_MOUNT_ATTR_PTR)
		DEFINE_PRINTER(SAT_STRUCT_DQBLK_PTR)
		DEFINE_PRINTER(SAT_CONST_STRUCT_LANDLOCK_RULESET_ATTR_PTR)
		DEFINE_PRINTER(SAT_STRUCT_FUTEX_WAITV_PTR)
		DEFINE_PRINTER(SAT_CACHESTAT_RANGE__USER_PTR)
		DEFINE_PRINTER(SAT_CACHESTAT__USER_PTR)
	};

	printer_table[type](data);
	return ;
}

DECLARE_PRINTER(SAT_VA_ARGS)
{
	printf("{...}");
}

DECLARE_PRINTER(SAT_STRUCT_KEXEC_SEGMENT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_INT)
{
	printf("%d", (int)data);
}

DECLARE_PRINTER(SAT_STRUCT_SIGALTSTACK_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UNION_BPF_ATTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_USER_MSGHDR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CHAR_PTR)
{
	printf("%p", (char *)data);
}

DECLARE_PRINTER(SAT_STRUCT__KERNEL_ITIMERSPEC_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CAP_USER_HEADER_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_CAP_USER_DATA_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_IOCB_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_MQD_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_SIZE_T)
{
	printf("%lu", (size_t)data);
}

DECLARE_PRINTER(SAT_OFF_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_PERF_EVENT_ATTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_SIGSET_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_OLD_UTSNAME_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_KEY_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UNSIGNED_INT)
{
	printf("%u", (unsigned int)data);
}

DECLARE_PRINTER(SAT_INT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_LOFF_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UNSIGNED_INT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_TIME_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_SCHED_PARAM_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_AIO_CONTEXT_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_OFF_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_QID_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT__KERNEL_TIMESPEC_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT__KERNEL_TIMEX_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_MQ_ATTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_RLIMIT64_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_STATFS_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_STRUCT__KERNEL_ITIMERSPEC_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_KEY_SERIAL_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_TIMER_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_RUSAGE_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UNSIGNED)
{
	printf("%u", (unsigned)data);
}

DECLARE_PRINTER(SAT_GID_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_STRUCT_SIGALTSTACK_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_EPOLL_EVENT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_SIZE_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_GETCPU_CACHE_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_LONG){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_U32_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_FILE_HANDLE_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_RLIMIT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_STRUCT_MQ_ATTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_MSQID_DS_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_IO_EVENT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_SYSINFO_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_TIMEZONE_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_SOCKADDR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UID_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_STRUCT_RLIMIT64_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_VOID_PTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_VOID_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CAP_USER_DATA_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_USTAT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_ROBUST_LIST_HEAD_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_SIGSET_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_UTIMBUF_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_STRUCT_SIGEVENT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CLOCKID_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_TIMER_T_PTR_){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_STRUCT_IOVEC_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_ITIMERVAL_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_STRUCT__KERNEL_TIMESPEC_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UNSIGNED_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_CHAR_PTR_){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_STATX_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_FD_SET_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_LINUX_DIRENT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_INT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UNSIGNED_LONG){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_SIGEVENT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT__S32){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_STAT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_GID_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_U64){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_SIGINFO_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_TMS_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_U32){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_SEMBUF_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_SHMID_DS_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_TIMEVAL_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT__OLD_KERNEL_STAT_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_LINUX_DIRENT64_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_CHAR_PTR_CONST_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_SIGACTION_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_AIO_CONTEXT_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_LOFF_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_MSGBUF_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_POLLFD_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_CHAR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_PID_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_MMSGHDR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_RWF_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UNSIGNED_CHAR_PTR_)
{
	printf("%s", (unsigned char *)data);
}

DECLARE_PRINTER(SAT_STRUCT_SCHED_ATTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_UNSIGNED_LONG_PTR)
{
	printf("%p", (unsigned long *)data);
}

DECLARE_PRINTER(SAT_CONST_STRUCT_SIGACTION_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_IOCB_PTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UMODE_T){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_ROBUST_LIST_HEAD_PTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UID_T_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_VOID_PTR)
{
	printf("%p", (void *)data);
}

DECLARE_PRINTER(SAT_STRUCT_SIGINFO_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_UNSIGNED_LONG_PTR)
{
	printf("%p", (unsigned long*)data);
}

DECLARE_PRINTER(SAT_STRUCT_USER_DESC_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_NO_ARG)
{
	printf("");
}

DECLARE_PRINTER(SAT_CONST_STRUCT_TIMESPEC_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_RSEQ_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_IO_URING_PARAMS_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_CLONE_ARGS_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_OPEN_HOW_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_IOVEC_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_MOUNT_ATTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_DQBLK_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CONST_STRUCT_LANDLOCK_RULESET_ATTR_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_STRUCT_FUTEX_WAITV_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CACHESTAT_RANGE__USER_PTR){printf("NOT IMPLEMENTED");}

DECLARE_PRINTER(SAT_CACHESTAT__USER_PTR){printf("NOT IMPLEMENTED");}
